/*
 * Mr. Kaune
 * This is a GUI program
 * September 16,2019
 */

/**
 *
 * @author rkaune
 */
public class frameGUI extends javax.swing.JFrame {

    /**
     * Creates new form frameGUI
     */
    public frameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGUI = new javax.swing.JPanel();
        labelPrompt = new javax.swing.JLabel();
        textMark1 = new javax.swing.JTextField();
        buttonDisplay = new javax.swing.JButton();
        labelDisplay = new javax.swing.JLabel();
        labelPrompt1 = new javax.swing.JLabel();
        textMark2 = new javax.swing.JTextField();
        textMark3 = new javax.swing.JTextField();
        textMark4 = new javax.swing.JTextField();
        labelPrompt2 = new javax.swing.JLabel();
        labelPrompt3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPrompt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelPrompt.setText("Enter your mark");

        textMark1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        buttonDisplay.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        buttonDisplay.setText("Press Me");
        buttonDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisplayActionPerformed(evt);
            }
        });

        labelDisplay.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        labelPrompt1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelPrompt1.setText("Enter your mark");

        textMark2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        textMark3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        textMark4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        labelPrompt2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelPrompt2.setText("Enter your mark");

        labelPrompt3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelPrompt3.setText("Enter your mark");

        javax.swing.GroupLayout panelGUILayout = new javax.swing.GroupLayout(panelGUI);
        panelGUI.setLayout(panelGUILayout);
        panelGUILayout.setHorizontalGroup(
            panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGUILayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelGUILayout.createSequentialGroup()
                        .addComponent(labelPrompt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textMark3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGUILayout.createSequentialGroup()
                        .addComponent(labelPrompt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textMark2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonDisplay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisplay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGUILayout.createSequentialGroup()
                        .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrompt1)
                            .addComponent(labelPrompt))
                        .addGap(52, 52, 52)
                        .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMark1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMark4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelGUILayout.setVerticalGroup(
            panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGUILayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrompt)
                    .addComponent(textMark4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrompt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrompt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrompt3))
                .addGap(24, 24, 24)
                .addComponent(buttonDisplay)
                .addGap(18, 18, 18)
                .addComponent(labelDisplay)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisplayActionPerformed
        double mark1 = Double.parseDouble(textMark1.getText());
        double mark2 = Double.parseDouble(textMark2.getText());
        double mark3 = Double.parseDouble(textMark3.getText());
        double mark4 = Double.parseDouble(textMark4.getText());
        double average = (mark1 + mark2 + mark3 + mark4) /4;
        average = average * 100;
        average = Math.round(average);
        average = average / 100;
        labelDisplay.setText("Hello " + average + " !");
    }//GEN-LAST:event_buttonDisplayActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDisplay;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelDisplay;
    private javax.swing.JLabel labelPrompt;
    private javax.swing.JLabel labelPrompt1;
    private javax.swing.JLabel labelPrompt2;
    private javax.swing.JLabel labelPrompt3;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JPanel panelGUI;
    private javax.swing.JTextField textMark1;
    private javax.swing.JTextField textMark2;
    private javax.swing.JTextField textMark3;
    private javax.swing.JTextField textMark4;
    // End of variables declaration//GEN-END:variables
}
